const express = require("express");
const axios = require("axios");

const savePurchase = require("../services/purchaseService");
const sendWelcomeEmail = require("../services/emailService");
const supabase = require("../config/supabase");

const router = express.Router();

const SUCCESS_PAGE =
    "https://skillforgeacademy5-sys.github.io/skillforge-academy/success.html";


    // =====================================
    // Initialize Payment
    // =====================================

    router.post("/initialize-payment", async (req, res) => {

        try {

                const {
                            email,
                                        amount,
                                                    courseName,
                                                                courseId,
                                                                            telegramLink
                                                                                    } = req.body;

                                                                                            const response = await axios.post(

                                                                                                        "https://api.paystack.co/transaction/initialize",

                                                                                                                    {

                                                                                                                                    email,

                                                                                                                                                    amount: Number(amount) * 100,

                                                                                                                                                                    callback_url: SUCCESS_PAGE,

                                                                                                                                                                                    metadata: {

                                                                                                                                                                                                        courseId,

                                                                                                                                                                                                                            courseName,

                                                                                                                                                                                                                                                telegramLink

                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                            },

                                                                                                                                                                                                                                                                                        {

                                                                                                                                                                                                                                                                                                        headers: {

                                                                                                                                                                                                                                                                                                                            Authorization:
                                                                                                                                                                                                                                                                                                                                                    `Bearer ${process.env.PAYSTACK_SECRET_KEY}`,

                                                                                                                                                                                                                                                                                                                                                                        "Content-Type": "application/json"

                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                    res.json({

                                                                                                                                                                                                                                                                                                                                                                                                                                success: true,

                                                                                                                                                                                                                                                                                                                                                                                                                                            authorization_url:
                                                                                                                                                                                                                                                                                                                                                                                                                                                            response.data.data.authorization_url,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        reference:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        response.data.data.reference

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        catch (err) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error(err.response?.data || err.message);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.status(500).json({

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    success: false,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                message: "Unable to initialize payment."

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // =====================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Verify Payment
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // =====================================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            router.post("/verify-payment", async (req, res) => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const { reference } = req.body;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const response = await axios.get(

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            `https://api.paystack.co/transaction/verify/${reference}`,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        headers: {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Authorization:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    `Bearer ${process.env.PAYSTACK_SECRET_KEY}`

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const payment = response.data.data;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (payment.status !== "success") {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return res.json({

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    success: false,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    message: "Payment failed."

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const { data: existing } = await supabase

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .from("purchases")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .select("id")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .eq("reference", payment.reference)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .maybeSingle();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!existing) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await savePurchase(payment);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await sendWelcomeEmail(

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                payment.customer.email,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                payment.metadata.courseName,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                payment.metadata.telegramLink

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.json({

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        success: true,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    redirect: SUCCESS_PAGE

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    catch (err) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error(err.response?.data || err.message);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.status(500).json({

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                success: false,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            message: "Verification failed."

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        module.exports = router;